name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Transfer Build Artifacts to EC2
      run: |
        aws ssm send-command --targets Key=instanceids,Values=i-0edeabf9042d24990 --document-name "AWS-RunShellScript" --parameters commands="mkdir -p /home/root/project"

    - name: Deploy to EC2
      run: |
        aws ssm send-command --targets Key=instanceids,Values=i-0edeabf9042d24990 --document-name "AWS-RunShellScript" --parameters commands="cd /home/ubuntu/project && base64 -d build.tar.gz.b64 | tar -xzvf - && npm install && npm start"

    - name: SSM into EC2 and Setup
      run: |
        aws ssm start-session --target i-0edeabf9042d24990 --document-name "AWS-StartInteractiveCommand" --parameters command-line="sudo -i && su ubuntu && cd /home/ubuntu/project"
